export const industries = [
  'Agriculture',
  'Construction',
  'Education',
  'Financial Services',
  'Healthcare',
  'Hospitality',
  'Information Technology',
  'Manufacturing',
  'Media & Entertainment',
  'Mining',
  'Oil & Gas',
  'Professional Services',
  'Real Estate',
  'Retail',
  'Telecommunications',
  'Transportation',
  'Utilities',
  'Wholesale Trade',
  'Other',
];
