import { useState } from 'react';
import DashboardLayout from '@/components/layout/DashboardLayout';
import { Card } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import EmptyState from '@/components/shared/EmptyState';
import { motion } from 'framer-motion';
import { FileText, Download, Filter, FileSpreadsheet, FilePieChart, ShieldCheck, Clock, CheckCircle2 } from 'lucide-react';
import { isDemoAccount } from '@/lib/utils/isDemoAccount';
import { useOnboardingStore } from '@/lib/store/onboardingStore';
import { toast } from 'sonner';
import jsPDF from 'jspdf';

interface Report {
  id: string;
  name: string;
  description: string;
  type: 'compliance' | 'financial' | 'tax' | 'audit';
  format: 'PDF' | 'Excel' | 'CSV';
  generatedAt: Date;
  size: string;
  status: 'ready' | 'generating' | 'scheduled';
}

const reportTemplates = [
  { id: 't1', name: 'FIRS Compliance Summary', description: 'Monthly compliance status for all submitted invoices', icon: ShieldCheck, type: 'compliance' as const },
  { id: 't2', name: 'Revenue & Profit Report', description: 'Detailed revenue breakdown by source and client', icon: FilePieChart, type: 'financial' as const },
  { id: 't3', name: 'Tax Remittance Report', description: 'VAT and withholding tax summary for FIRS filing', icon: FileSpreadsheet, type: 'tax' as const },
  { id: 't4', name: 'Audit Trail Report', description: 'Complete activity log for compliance auditing', icon: FileText, type: 'audit' as const },
];

const recentReports: Report[] = [
  { id: '1', name: 'FIRS Compliance Summary - Dec 2024', type: 'compliance', format: 'PDF', generatedAt: new Date(Date.now() - 86400000), size: '2.4 MB', status: 'ready', description: '' },
  { id: '2', name: 'Revenue Report Q4 2024', type: 'financial', format: 'Excel', generatedAt: new Date(Date.now() - 86400000 * 3), size: '5.1 MB', status: 'ready', description: '' },
  { id: '3', name: 'Tax Remittance - Dec 2024', type: 'tax', format: 'PDF', generatedAt: new Date(Date.now() - 86400000 * 5), size: '1.8 MB', status: 'ready', description: '' },
  { id: '4', name: 'Monthly Audit Trail - Dec 2024', type: 'audit', format: 'CSV', generatedAt: new Date(Date.now() - 86400000 * 7), size: '3.2 MB', status: 'ready', description: '' },
  { id: '5', name: 'FIRS Compliance Summary - Jan 2025', type: 'compliance', format: 'PDF', generatedAt: new Date(), size: '—', status: 'generating', description: '' },
];

const typeColors: Record<string, string> = {
  compliance: 'bg-primary/10 text-primary border-primary/20',
  financial: 'bg-success/10 text-success border-success/20',
  tax: 'bg-warning/10 text-warning-foreground border-warning/20',
  audit: 'bg-info/10 text-info border-info/20',
};

function generatePDF(name: string) {
  const doc = new jsPDF();
  doc.setFontSize(18);
  doc.text('Elexsol Report', 20, 25);
  doc.setFontSize(14);
  doc.text(name, 20, 40);
  doc.setFontSize(10);
  doc.text(`Generated: ${new Date().toLocaleDateString('en-NG')}`, 20, 55);
  doc.text('Organization: Elexsol Technologies Ltd', 20, 65);
  doc.setFontSize(11);
  doc.text('Summary', 20, 85);
  doc.setFontSize(9);
  const lines = [
    'Total Invoices Processed: 1,247',
    'FIRS Validated: 1,198 (96.1%)',
    'Flagged for Review: 49 (3.9%)',
    'Total Revenue: ₦84,500,000',
    'Tax Remitted: ₦6,337,500',
    'Average Payment Velocity: 14 days',
  ];
  lines.forEach((line, i) => doc.text(line, 20, 100 + i * 10));
  doc.setFontSize(8);
  doc.text('This report is system-generated by Elexsol Compliance Gateway.', 20, 180);
  doc.save(`${name.replace(/\s+/g, '-').toLowerCase()}.pdf`);
}

function generateCSV(name: string) {
  const csv = 'Invoice,Customer,Amount,Tax,Status,Date\nINV-2024-0847,Dangote Industries,4500000,337500,Flagged,15-Dec-2024\nINV-2024-0848,MTN Nigeria,2800000,210000,Approved,16-Dec-2024\nINV-2024-0849,Access Bank Plc,1200000,90000,Submitted,17-Dec-2024\n';
  const blob = new Blob([csv], { type: 'text/csv' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${name.replace(/\s+/g, '-').toLowerCase()}.csv`;
  a.click();
  URL.revokeObjectURL(url);
}

export default function ReportsPage() {
  const [typeFilter, setTypeFilter] = useState<string>('all');
  const [generating, setGenerating] = useState<string | null>(null);
  const demo = isDemoAccount();
  const { isOnboardingComplete } = useOnboardingStore();
  const showPopulated = demo || isOnboardingComplete();

  const filtered = typeFilter === 'all' ? recentReports : recentReports.filter(r => r.type === typeFilter);

  const handleGenerate = (template: typeof reportTemplates[0]) => {
    setGenerating(template.id);
    toast.info(`Generating ${template.name}...`);
    setTimeout(() => {
      generatePDF(template.name);
      setGenerating(null);
      toast.success(`${template.name} downloaded`);
    }, 1200);
  };

  const handleDownload = (report: Report) => {
    if (report.format === 'CSV') {
      generateCSV(report.name);
    } else {
      generatePDF(report.name);
    }
    toast.success(`${report.name} downloaded`);
  };

  if (!showPopulated) {
    return (
      <DashboardLayout title="Reports" subtitle="Generate compliance & financial reports">
        <EmptyState
          icon={FileText}
          title="Automated Reporting Engine"
          description="Elexsol generates FIRS compliance summaries, revenue reports, tax remittance filings, and audit trail exports automatically. Complete your setup to start generating reports."
          ctaLabel="Complete Setup"
          ctaLink="/settings"
        />
      </DashboardLayout>
    );
  }

  return (
    <DashboardLayout title="Reports" subtitle="Generate compliance & financial reports">
      {/* Report Templates */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
        {reportTemplates.map((template, i) => (
          <motion.div key={template.id} initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.08 }}>
            <Card className="p-5 shadow-card border-none hover:shadow-elevated transition-shadow cursor-pointer group">
              <div className="w-11 h-11 rounded-xl bg-primary/8 flex items-center justify-center mb-3 group-hover:scale-105 transition-transform">
                <template.icon className="w-5 h-5 text-primary" />
              </div>
              <h3 className="text-sm font-semibold text-foreground mb-1">{template.name}</h3>
              <p className="text-xs text-muted-foreground mb-3">{template.description}</p>
              <Button
                size="sm"
                className="w-full text-xs"
                disabled={generating === template.id}
                onClick={() => handleGenerate(template)}
              >
                {generating === template.id ? 'Generating...' : 'Generate Report'}
              </Button>
            </Card>
          </motion.div>
        ))}
      </div>

      {/* Recent Reports */}
      <Card className="p-5 shadow-card border-none">
        <div className="flex items-center justify-between mb-4 flex-wrap gap-3">
          <h3 className="text-sm font-semibold text-foreground">Recent Reports</h3>
          <div className="flex items-center gap-2">
            <Select value={typeFilter} onValueChange={setTypeFilter}>
              <SelectTrigger className="w-40 h-8 text-xs">
                <Filter className="w-3.5 h-3.5 mr-1.5" />
                <SelectValue placeholder="Filter by type" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Types</SelectItem>
                <SelectItem value="compliance">Compliance</SelectItem>
                <SelectItem value="financial">Financial</SelectItem>
                <SelectItem value="tax">Tax</SelectItem>
                <SelectItem value="audit">Audit</SelectItem>
              </SelectContent>
            </Select>
          </div>
        </div>

        <div className="space-y-2">
          {filtered.map((report, i) => (
            <motion.div
              key={report.id}
              initial={{ opacity: 0, x: -8 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: 0.2 + i * 0.06 }}
              className="flex items-center justify-between py-3 px-3 rounded-lg hover:bg-muted/50 transition-colors"
            >
              <div className="flex items-center gap-3 flex-1 min-w-0">
                <div className="w-9 h-9 rounded-lg bg-muted flex items-center justify-center flex-shrink-0">
                  <FileText className="w-4 h-4 text-muted-foreground" />
                </div>
                <div className="min-w-0">
                  <p className="text-sm font-medium text-foreground truncate">{report.name}</p>
                  <div className="flex items-center gap-2 mt-0.5">
                    <span className="text-xs text-muted-foreground">{report.format}</span>
                    <span className="text-xs text-muted-foreground">•</span>
                    <span className="text-xs text-muted-foreground">{report.size}</span>
                    <span className="text-xs text-muted-foreground">•</span>
                    <span className="text-xs text-muted-foreground">
                      {report.generatedAt.toLocaleDateString('en-NG', { day: 'numeric', month: 'short', year: 'numeric' })}
                    </span>
                  </div>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <Badge variant="outline" className={`text-xs ${typeColors[report.type]}`}>
                  {report.type}
                </Badge>
                {report.status === 'ready' ? (
                  <Button variant="outline" size="sm" className="text-xs" onClick={() => handleDownload(report)}>
                    <Download className="w-3.5 h-3.5 mr-1" /> Download
                  </Button>
                ) : report.status === 'generating' ? (
                  <Badge variant="outline" className="text-xs bg-muted animate-pulse">
                    <Clock className="w-3 h-3 mr-1" /> Generating...
                  </Badge>
                ) : null}
              </div>
            </motion.div>
          ))}
        </div>
      </Card>
    </DashboardLayout>
  );
}
